name: cargo_test
run-name: testing by cargo test
on: pull_request
jobs:
  cargo_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions-rs/cargo@v1
        with:
          command: test
